version: "3"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app/:/app
    command: ["bash", "-c", "make setup && make dev"]
  
  caddy:
    image: caddy:2-alpine
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app